"""Initial migration

Revision ID: 13c8ccd7022d
Revises: edca5632613b
Create Date: 2025-08-07 18:21:18.037725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13c8ccd7022d'
down_revision: Union[str, None] = 'edca5632613b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_baby_development_active', 'baby_development', ['is_active'], unique=False)
    op.create_index('ix_baby_development_day', 'baby_development', ['day_of_pregnancy'], unique=False)
    op.create_index('ix_baby_development_week', 'baby_development', ['week_number'], unique=False)
    op.create_index('ix_baby_development_week_trimester', 'baby_development', ['week_number', 'trimester'], unique=False)
    op.drop_index(op.f('idx_comments_post_created'), table_name='comments')
    op.drop_index(op.f('idx_family_members_pregnancy_user'), table_name='family_members')
    op.alter_column('posts', 'celebration_trigger_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('posts', 'emotional_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_posts_pregnancy_status_created'), table_name='posts')
    op.drop_index(op.f('idx_posts_trending'), table_name='posts')
    op.drop_index(op.f('idx_posts_type_created'), table_name='posts')
    op.drop_index(op.f('idx_reactions_post_user'), table_name='reactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_reactions_post_user'), 'reactions', ['post_id', 'user_id'], unique=False)
    op.create_index(op.f('idx_posts_type_created'), 'posts', ['type', 'created_at'], unique=False)
    op.create_index(op.f('idx_posts_trending'), 'posts', ['pregnancy_id', 'created_at', 'reaction_count', 'comment_count'], unique=False)
    op.create_index(op.f('idx_posts_pregnancy_status_created'), 'posts', ['pregnancy_id', 'status', 'created_at'], unique=False)
    op.alter_column('posts', 'emotional_context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('posts', 'celebration_trigger_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_family_members_pregnancy_user'), 'family_members', ['pregnancy_id', 'user_id', 'status'], unique=False)
    op.create_index(op.f('idx_comments_post_created'), 'comments', ['post_id', 'created_at'], unique=False)
    op.drop_index('ix_baby_development_week_trimester', table_name='baby_development')
    op.drop_index('ix_baby_development_week', table_name='baby_development')
    op.drop_index('ix_baby_development_day', table_name='baby_development')
    op.drop_index('ix_baby_development_active', table_name='baby_development')
    # ### end Alembic commands ###