"""Add Comment-User relationship

Revision ID: 44fe28c51a8d
Revises: 2c7dd7bb6e65
Create Date: 2025-08-04 16:42:56.106779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fe28c51a8d'
down_revision: Union[str, None] = '2c7dd7bb6e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###